version: "2.2"

services:
  backend:
    image: visual-app-backend:latest
    restart: always
    ports:
      - "${WEB_PORT}:3000"
    environment:
      - NODE_ENV=production
      - TARGET_API=${TARGET_API}
      - ENABLE_SECONDARY_AI_PROXY=false
    volumes:
      # 数据持久化目录 (Data persistence)
      - ./data/maps:/app/maps
      - ./data/image:/app/image
      - ./data/animal-species:/app/animal-species
      - ./data/videos:/app/videos
      - ./data/temp:/app/temp
      
      # 配置文件持久化 (Config persistence)
      # 建议首次部署使用 named volume 保留镜像内的配置，
      # 后续如果有修改需求，可以 cp 出来后改为 bind mount
      - app_config:/app/config
    mem_limit: 4g

volumes:
  app_config:
